platform :ios, '9.0'
use_frameworks!

target 'MarvelComics' do
	pod 'BothamNetworking', '~> 1.0'
    pod 'CryptoSwift', '~> 0.2'
    pod 'SDWebImage', '~> 3.7'
end

target 'MarvelComicsTests' do

end

target 'MarvelComicsUITests' do

end

